### ISSUE TITLE
Serverumstellungen geonova.no => geobuzz.no

### ISSUE THREAD

**Issue by diplomod** [diplomod/geobuzz#1]
Angenommenen Falles, Lukas und ich stemmen das Teil das Wochenende - kann Martin die Umstellungen ebenfalls bis Montag machen (oder im Zweifelsfall am Montag)?

**Comment by philipdomann** [comment]
Ich frage ihn, ob er am Montag Zeit hast....

**Comment by diplomod** [comment]
Ales klar, danke. Wobei siehe meine letzte Mail - habe das mit Lukas besprochen und wir würden es doch nochmal etwas anders machen - das hat vermutlich Auswirkungen auf Martins Task:


- Achtung: Neue Strategie: geonova.no => geonova.no/geobuzz (statt geobuzz.no alleine und hüpfen zwischen den URLs)
- Besucher von geonova.no werden automaisch auf geonova.no/geobuzz weiter geleitet. Das ist die Startseite.
- Besucher von geobuzz.no werden ebenfalls auf geonova.no/geobuzz umgeleitet
- geonova.no/news soll durch geonova.no/geobuzz/news ersetzt werden
- Unterseiten der news können dann wie aktuell auf Geonova diese URL haben: geonova.no/geobuzz/news-page/news-titel-123
- geonova.no alleine ist dann erst mal nicht erreichbar
- Frage: Wie verhält es sich "alten Links"? z.B. http://www.geonova.no/news-page/geokalender-2015-juni-nordryggen-forteller-historien/

**Comment by philipdomann** [comment]
Die Mail habe ich schon gesehen, danke!
